Traceback (most recent call last):
  File "/opt/anaconda3/envs/JupyterBook/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/JupyterBook/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/JupyterBook/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/JupyterBook/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/JupyterBook/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/opt/anaconda3/envs/JupyterBook/lib/python3.11/site-packages/nbclient/client.py", line 654, in async_setup_kernel
    yield
  File "/opt/anaconda3/envs/JupyterBook/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/JupyterBook/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/JupyterBook/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from qiskit_ibm_runtime import QiskitRuntimeService

service = QiskitRuntimeService(
    channel='ibm_quantum',
    instance='ibm-q/open/main',
    token='###########'
)

# Or save your credentials on disk.
QiskitRuntimeService.save_account(channel='ibm_quantum', instance='ibm-q/open/main', token='###########')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mqiskit_ibm_runtime[39;00m [38;5;28;01mimport[39;00m QiskitRuntimeService
[1;32m      3[0m service [38;5;241m=[39m QiskitRuntimeService(
[1;32m      4[0m     channel[38;5;241m=[39m[38;5;124m'[39m[38;5;124mibm_quantum[39m[38;5;124m'[39m,
[1;32m      5[0m     instance[38;5;241m=[39m[38;5;124m'[39m[38;5;124mibm-q/open/main[39m[38;5;124m'[39m,
[1;32m      6[0m     token[38;5;241m=[39m[38;5;124m'[39m[38;5;124m###########[39m[38;5;124m'[39m
[1;32m      7[0m )
[1;32m      9[0m [38;5;66;03m# Or save your credentials on disk.[39;00m

[0;31mModuleNotFoundError[0m: No module named 'qiskit_ibm_runtime'

